### ISSUE TITLE
npm install fail using Node 8

### ISSUE THREAD

**Issue by devism** [zerostaticthemes/gatsby-serif-theme#10]
11 warnings and 3 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ism/Desktop/TTM/ttm_site_2020/gatsby-serif-theme/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/ism/.nvm/versions/node/v12.8.1/bin/node" "/Users/ism/Desktop/TTM/ttm_site_2020/gatsby-serif-theme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/ism/Desktop/TTM/ttm_site_2020/gatsby-serif-theme/node_modules/node-sass
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN eslint-config-react-app@3.0.0-next.66cc7a90 requires a peer of babel-eslint@^8.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@3.0.0-next.66cc7a90 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-serif-theme@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ism/.npm/_logs/2020-06-23T20_20_18_104Z-debug.log

**Comment by jamesacampbell** [comment]
Yeah I am getting the same thing. Can't install.

**Comment by camoore1979** [comment]
Try the following. The problem is that this starter is 2 years old and you are running a newer node version that does not work with the specified `node-sass` in this repo's `package.json`. You've got to align your `node` and `node-sass` versions. See https://www.npmjs.com/package/node-sass and https://github.com/sass/node-sass/releases.

This worked for me:

1. `rm -rf ./node_modules`

2. `rm -f ./package-lock.json`

3. Update `package.json` to `node-sass` version `"^4.14.1". 

4. Now run `npm i`

**Comment by JugglerX** [comment]
@camoore1979 thank you for helping with this issue.

I've made a large update and refresh to the theme and have updated all the main dependancies. I had to use Node 10 to get it to run.
